/** Estilos compartidos de pantallas operativas */
export const page = {
  wrap: { fontFamily: 'Georgia, "Times New Roman", serif', color: '#081c15' },
  title: { margin: '0 0 0.25rem', color: '#1b4332', fontSize: '1.6rem' },
  sub: { margin: '0 0 1.25rem', color: '#52796f' },
  row: { display: 'flex', gap: '0.75rem', flexWrap: 'wrap', marginBottom: '1rem', alignItems: 'center' },
  input: {
    padding: '0.55rem 0.65rem',
    border: '1px solid #95d5b2',
    borderRadius: 2,
    minWidth: 160,
  },
  select: {
    padding: '0.55rem 0.65rem',
    border: '1px solid #95d5b2',
    borderRadius: 2,
    minWidth: 140,
  },
  btn: {
    padding: '0.55rem 1rem',
    background: '#1b4332',
    color: '#fff',
    border: 'none',
    borderRadius: 2,
    cursor: 'pointer',
  },
  btnGhost: {
    padding: '0.55rem 1rem',
    background: '#fff',
    color: '#1b4332',
    border: '1px solid #1b4332',
    borderRadius: 2,
    cursor: 'pointer',
  },
  btnDanger: {
    padding: '0.4rem 0.7rem',
    background: '#9b2226',
    color: '#fff',
    border: 'none',
    borderRadius: 2,
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  table: { width: '100%', borderCollapse: 'collapse', marginTop: '0.5rem' },
  th: {
    textAlign: 'left',
    padding: '0.65rem',
    borderBottom: '2px solid #1b4332',
    background: '#d8f3dc',
  },
  td: { padding: '0.6rem', borderBottom: '1px solid #b7e4c7' },
  card: {
    background: '#fff',
    border: '1px solid #b7e4c7',
    padding: '1rem',
    marginBottom: '1rem',
  },
  error: {
    background: '#fff0f0',
    color: '#9b2226',
    padding: '0.75rem',
    marginBottom: '1rem',
    borderLeft: '3px solid #9b2226',
  },
  ok: {
    background: '#d8f3dc',
    color: '#1b4332',
    padding: '0.75rem',
    marginBottom: '1rem',
    borderLeft: '3px solid #1b4332',
  },
};
