export const CATALOGS_SERVICE = Symbol('CUYES_CATALOGS_SERVICE');
export const MOVEMENTS_SERVICE = Symbol('CUYES_MOVEMENTS_SERVICE');
export const SALES_SERVICE = Symbol('CUYES_SALES_SERVICE');
export const INVENTORY_SERVICE = Symbol('CUYES_INVENTORY_SERVICE');
export const REPORTS_SERVICE = Symbol('CUYES_REPORTS_SERVICE');
export const BREEDINGS_SERVICE = Symbol('CUYES_BREEDINGS_SERVICE');
export const BIRTHS_SERVICE = Symbol('CUYES_BIRTHS_SERVICE');
export const WEANINGS_SERVICE = Symbol('CUYES_WEANINGS_SERVICE');
export const ALERTS_SERVICE = Symbol('CUYES_ALERTS_SERVICE');
export const RANKING_SERVICE = Symbol('CUYES_RANKING_SERVICE');

export const CUYES_SERVICE_TOKENS = {
  catalogs: CATALOGS_SERVICE,
  movements: MOVEMENTS_SERVICE,
  sales: SALES_SERVICE,
  inventory: INVENTORY_SERVICE,
  reports: REPORTS_SERVICE,
  breedings: BREEDINGS_SERVICE,
  births: BIRTHS_SERVICE,
  weanings: WEANINGS_SERVICE,
  alerts: ALERTS_SERVICE,
  ranking: RANKING_SERVICE,
} as const;
