import type { CSSProperties } from 'react';

/**
 * Tema institucional — Facultad de Zootecnia · UNAS
 * Crema + rojo oscuro, formas suaves (no “caja recta”).
 */
export const theme = {
  cream: '#F4EDE2',
  creamSoft: '#FFFCFA',
  creamDeep: '#E6DCCB',
  maroon: '#7A1216',
  maroonDeep: '#4F0C10',
  maroonSoft: '#A33A3E',
  ink: '#2C181A',
  muted: '#7A6358',
  border: '#E0D3BF',
  white: '#FFFFFF',
  danger: '#9B1C1F',
  okBg: '#EFE8DA',
  errorBg: '#FBECEC',
  fontDisplay: '"Fraunces", "Libre Baskerville", Georgia, serif',
  fontBody: '"Source Sans 3", "Segoe UI", system-ui, sans-serif',
  shadow: '0 12px 28px rgba(79, 12, 16, 0.09)',
  shadowSoft: '0 6px 16px rgba(79, 12, 16, 0.06)',
  radius: 10,
  radiusSm: 8,
  radiusLg: 14,
};

/** Estilos compartidos de pantallas operativas */
export const page: Record<string, CSSProperties> = {
  wrap: {
    fontFamily: theme.fontBody,
    color: theme.ink,
  },
  title: {
    margin: '0 0 0.35rem',
    color: theme.maroonDeep,
    fontSize: '1.85rem',
    fontFamily: theme.fontDisplay,
    fontWeight: 650,
    letterSpacing: '-0.02em',
  },
  sub: {
    margin: '0 0 1.5rem',
    color: theme.muted,
    fontSize: '1.02rem',
    lineHeight: 1.45,
  },
  row: {
    display: 'flex',
    gap: '0.7rem',
    flexWrap: 'wrap',
    marginBottom: '1.1rem',
    alignItems: 'center',
  },
  input: {
    padding: '0.65rem 0.9rem',
    border: `1px solid ${theme.border}`,
    borderRadius: theme.radiusSm,
    minWidth: 160,
    background: theme.creamSoft,
    color: theme.ink,
    fontFamily: theme.fontBody,
    outline: 'none',
    boxShadow: 'inset 0 1px 2px rgba(79,12,16,0.04)',
  },
  select: {
    padding: '0.65rem 0.9rem',
    border: `1px solid ${theme.border}`,
    borderRadius: theme.radiusSm,
    minWidth: 140,
    background: theme.creamSoft,
    color: theme.ink,
    fontFamily: theme.fontBody,
    outline: 'none',
  },
  btn: {
    padding: '0.65rem 1.25rem',
    background: `linear-gradient(180deg, ${theme.maroonSoft} 0%, ${theme.maroon} 100%)`,
    color: theme.creamSoft,
    border: 'none',
    borderRadius: theme.radiusSm,
    cursor: 'pointer',
    fontFamily: theme.fontBody,
    fontWeight: 650,
    boxShadow: '0 4px 12px rgba(122, 18, 22, 0.18)',
    textDecoration: 'none',
    display: 'inline-block',
  },
  btnGhost: {
    padding: '0.62rem 1.2rem',
    background: theme.creamSoft,
    color: theme.maroon,
    border: `1px solid ${theme.border}`,
    borderRadius: theme.radiusSm,
    cursor: 'pointer',
    fontFamily: theme.fontBody,
    fontWeight: 650,
    textDecoration: 'none',
    display: 'inline-block',
  },
  btnDanger: {
    padding: '0.52rem 0.95rem',
    minWidth: 92,
    background: theme.danger,
    color: '#fff',
    border: `1px solid ${theme.danger}`,
    borderRadius: theme.radiusSm,
    cursor: 'pointer',
    fontSize: '0.85rem',
    fontWeight: 650,
    fontFamily: theme.fontBody,
    textAlign: 'center',
    lineHeight: 1.25,
    boxSizing: 'border-box',
    display: 'inline-block',
  },
  /** Botones compactos en filas de tabla (misma caja para outline y danger). */
  btnRow: {
    padding: '0.52rem 0.95rem',
    minWidth: 92,
    fontSize: '0.85rem',
    fontWeight: 650,
    borderRadius: theme.radiusSm,
    cursor: 'pointer',
    fontFamily: theme.fontBody,
    textAlign: 'center' as const,
    lineHeight: 1.25,
    boxSizing: 'border-box' as const,
    display: 'inline-block',
  },
  btnRowOutline: {
    background: theme.creamSoft,
    color: theme.maroon,
    border: `1px solid ${theme.border}`,
  },
  btnRowDanger: {
    background: theme.danger,
    color: '#fff',
    border: `1px solid ${theme.danger}`,
  },
  tableWrap: {
    marginTop: '0.25rem',
    borderRadius: theme.radiusLg,
    border: `1px solid ${theme.border}`,
    overflow: 'hidden',
    boxShadow: theme.shadowSoft,
    background: theme.creamSoft,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    borderSpacing: 0,
  },
  th: {
    textAlign: 'left',
    padding: '0.85rem 1rem',
    background: theme.creamDeep,
    color: theme.maroonDeep,
    fontFamily: theme.fontBody,
    fontWeight: 700,
    fontSize: '0.92rem',
    borderBottom: `1px solid ${theme.border}`,
  },
  td: {
    padding: '0.8rem 1rem',
    borderBottom: `1px solid ${theme.border}`,
    color: theme.ink,
    background: theme.creamSoft,
  },
  card: {
    background: theme.creamSoft,
    border: `1px solid ${theme.border}`,
    padding: '1.25rem 1.35rem',
    marginBottom: '1.15rem',
    borderRadius: theme.radius,
    boxShadow: theme.shadowSoft,
  },
  error: {
    background: theme.errorBg,
    color: theme.danger,
    padding: '0.85rem 1rem',
    marginBottom: '1rem',
    borderRadius: theme.radiusSm,
    border: '1px solid rgba(155,28,31,0.18)',
  },
  ok: {
    background: theme.okBg,
    color: theme.maroonDeep,
    padding: '0.85rem 1rem',
    marginBottom: '1rem',
    borderRadius: theme.radiusSm,
    border: `1px solid ${theme.border}`,
  },
};
